export const USER_SIGN_UP_USER_BEGIN = 'USER_SIGN_UP_USER_BEGIN';
export const USER_SIGN_UP_USER_SUCCESS = 'USER_SIGN_UP_USER_SUCCESS';
export const USER_SIGN_UP_USER_FAILURE = 'USER_SIGN_UP_USER_FAILURE';
export const USER_SIGN_UP_USER_DISMISS_ERROR = 'USER_SIGN_UP_USER_DISMISS_ERROR';
export const USER_LOGIN_USER_BEGIN = 'USER_LOGIN_USER_BEGIN';
export const USER_LOGIN_USER_SUCCESS = 'USER_LOGIN_USER_SUCCESS';
export const USER_LOGIN_USER_FAILURE = 'USER_LOGIN_USER_FAILURE';
export const USER_LOGIN_USER_DISMISS_ERROR = 'USER_LOGIN_USER_DISMISS_ERROR';
